apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "firebat-ec.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "firebat-ec.labels" . | nindent 4 }}
data:
  config.json: {{ .Values.daemon.config | quote }}
